# Generated by Django 5.0.4 on 2024-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_web', '0018_alter_otptoken_otp_code_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1ff3f6', max_length=6),
        ),
    ]
